
/**
 * Extra modification for CocoaPress Printers
 */

//#define HOTENDS
//#define COCOA_PRESS_EXTRUDER
//#define TOUCH_UI_COCOA_PRESS
//#define TOUCH_UI_COCOA_THEME
//#define TOUCH_UI_LCD_TEMP_SCALING
//#define COCOA_PRESS_PREHEAT_SECONDS
//#define COCOA_PRESS_PREHEAT_DARK_CHOCOLATE_INT_SCRIPT
//#define COCOA_PRESS_PREHEAT_MILK_CHOCOLATE_INT_SCRIPT
//#define COCOA_PRESS_PREHEAT_WHITE_CHOCOLATE_INT_SCRIPT
//#define COCOA_PRESS_PREHEAT_DARK_CHOCOLATE_EXT_SCRIPT
//#define COCOA_PRESS_PREHEAT_MILK_CHOCOLATE_EXT_SCRIPT
//#define COCOA_PRESS_PREHEAT_WHITE_CHOCOLATE_EXT_SCRIPT
//#define DISABLE_DUE_SD_MMC
//#define ARCHIM2_SPI_FLASH_EEPROM_BACKUP_SIZE
//#define TOUCH_UI_FILAMENT_RUNOUT_WORKAROUNDS
//#define NO_TIME_AFTER_SD_PRINT
//#define NO_PAUSE_FOR_REHEAT
//#define BED_LEVELING_COMMANDS
//#define COCOA_PRESS_EXTRA_HEATER